name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      push:
        description: "Push source strings and translations to Transifex"
        type: boolean
      pull:
        description: "Pull translations from Transifex"
        type: boolean
  schedule:
    - cron: '0 14 * * 5'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
env:
  TX_CLI_VERSION: '1.6.16'
  TX_PROJECT: python-newest  # Project name for the latest python version

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      all_versions: ${{ steps.version.outputs.all_versions }}
      current: ${{ steps.version.outputs.current }}
      version_pairs: ${{ steps.version.outputs.version_pairs }}
      languages: ${{ steps.languages.outputs.languages }}
    steps:
    - name: Check out ${{ github.repository }}
      uses: actions/checkout@v4.2.1

    - name: Set up Python 3
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt

    - name: Set version variables
      id: version
      run: |
        echo "all_versions=$(scripts/manage_versions.py all)" >> $GITHUB_OUTPUT
        echo "current=$(scripts/manage_versions.py current)" >> $GITHUB_OUTPUT
        echo "version_pairs=$(scripts/manage_versions.py generate_pairs)" >> $GITHUB_OUTPUT
    
    - name: Check out branch ${{ steps.version.outputs.current }}
      uses: actions/checkout@v4.2.1
      with:
        ref: ${{ steps.version.outputs.current }}      
        path: ${{ steps.version.outputs.current }}
    
    - name: Set languages variable
      id: languages
      working-directory: ${{ steps.version.outputs.current }}
      run: |
        echo "languages=$(../scripts/list-langs.py)" >> $GITHUB_OUTPUT

    - name: Print variables values
      run: |
        echo all_versions: ${{ steps.version.outputs.all_versions }}
        echo current: ${{ steps.version.outputs.current }}
        echo version_pairs: ${{ steps.version.outputs.version_pairs }}
        echo languages: ${{ steps.languages.outputs.languages }}
        
  call-check:
    uses: ./.github/workflows/check.yml
    needs: trigger
    with:
      cpython_version: ${{ needs.trigger.outputs.current }}
      languages: ${{ needs.trigger.outputs.languages }}
    secrets: inherit
